-- https://blog.sql-workbench.eu/post/unpivot-with-postgres/
drop table if exists osm_entity_tags;

create table if not exists osm_entity_tags as 
(
		select pr.osm_id, 'swpa_roads' as osm_table, pr.id, v.tag_name, v.tag_value, st_transform(pr.way, 32617) as geometry
		from osm.swpa_roads pr
		cross join lateral (
			values 
				('access', pr.access),
				('admin_level', pr.admin_level),
				('aerialway', pr.aerialway),
				('aeroway', pr.aeroway),
				('amenity', pr.amenity),
				('area', pr.area),
				('barrier', pr.barrier),
				('bicycle', pr.bicycle),
				('brand', pr.brand),
				('bridge', pr.bridge),
				('boundary', pr.boundary),
				('building', pr.building),
				('construction', pr.construction),
				('covered', pr.covered),
				('culvert', pr.culvert),
				('cutting', pr.cutting),
				('denomination', pr.denomination),
				('disused', pr.disused),
				('embankment', pr.embankment),
				('foot', pr.foot),
				('harbour', pr.harbour),
				('highway', pr.highway),
				('historic', pr.historic),
				('horse', pr.horse),
				('intermittent', pr.intermittent),
				('junction', pr.junction),
				('landuse', pr.landuse),
				('leisure', pr.leisure),
				('lock', pr.lock),
				('man_made', pr.man_made),
				('military', pr.military),
				('motorcar', pr.motorcar),
				('natural', pr.natural),
				('office', pr.office),
				('oneway', pr.oneway),
				('operator', pr.operator),
				('place', pr.place),
				('population', pr.population),
				('power', pr.power),
				('power_source', pr.power_source),
				('public_transport', pr.public_transport),
				('railway', pr.railway),
				('religion', pr.religion),
				('route', pr.route),
				('service', pr.service),
				('shop', pr.shop),
				('sport', pr.sport),
				('surface', pr.surface),
				('toll', pr.toll),
				('tourism', pr.tourism),
				('tracktype', pr.tracktype),
				('tunnel', pr.tunnel),
				('water', pr.water),
				('waterway', pr.waterway),
				('wetland', pr.wetland),
				('wood', pr.wood)
			) as v(tag_name, tag_value)
		where tag_value is not NULL
)
UNION ALL
(
		select pr.osm_id, 'swpa_line' as osm_table, pr.id, v.tag_name, v.tag_value, st_transform(pr.way, 32617) as geometry
		from osm.swpa_line pr
		cross join lateral (
			values 
				('access', pr.access),
				('admin_level', pr.admin_level),
				('aerialway', pr.aerialway),
				('aeroway', pr.aeroway),
				('amenity', pr.amenity),
				('area', pr.area),
				('barrier', pr.barrier),
				('bicycle', pr.bicycle),
				('brand', pr.brand),
				('bridge', pr.bridge),
				('boundary', pr.boundary),
				('building', pr.building),
				('construction', pr.construction),
				('covered', pr.covered),
				('culvert', pr.culvert),
				('cutting', pr.cutting),
				('denomination', pr.denomination),
				('disused', pr.disused),
				('embankment', pr.embankment),
				('foot', pr.foot),
				('harbour', pr.harbour),
				('highway', pr.highway),
				('historic', pr.historic),
				('horse', pr.horse),
				('intermittent', pr.intermittent),
				('junction', pr.junction),
				('landuse', pr.landuse),
				('leisure', pr.leisure),
				('lock', pr.lock),
				('man_made', pr.man_made),
				('military', pr.military),
				('motorcar', pr.motorcar),
				('natural', pr.natural),
				('office', pr.office),
				('oneway', pr.oneway),
				('operator', pr.operator),
				('place', pr.place),
				('population', pr.population),
				('power', pr.power),
				('power_source', pr.power_source),
				('public_transport', pr.public_transport),
				('railway', pr.railway),
				('religion', pr.religion),
				('route', pr.route),
				('service', pr.service),
				('shop', pr.shop),
				('sport', pr.sport),
				('surface', pr.surface),
				('toll', pr.toll),
				('tourism', pr.tourism),
				('tracktype', pr.tracktype),
				('tunnel', pr.tunnel),
				('water', pr.water),
				('waterway', pr.waterway),
				('wetland', pr.wetland),
				('wood', pr.wood)
			) as v(tag_name, tag_value)
		where tag_value is not NULL
)
UNION ALL
(
		select pr.osm_id, 'swpa_point' as osm_table, pr.id, v.tag_name, v.tag_value, st_transform(pr.way, 32617) as geometry
		from osm.swpa_point pr
		cross join lateral (
			values 
				('access', pr.access),
				('admin_level', pr.admin_level),
				('aerialway', pr.aerialway),
				('aeroway', pr.aeroway),
				('amenity', pr.amenity),
				('area', pr.area),
				('barrier', pr.barrier),
				('bicycle', pr.bicycle),
				('brand', pr.brand),
				('bridge', pr.bridge),
				('boundary', pr.boundary),
				('building', pr.building),
				('construction', pr.construction),
				('covered', pr.covered),
				('culvert', pr.culvert),
				('cutting', pr.cutting),
				('denomination', pr.denomination),
				('disused', pr.disused),
				('embankment', pr.embankment),
				('foot', pr.foot),
				('harbour', pr.harbour),
				('highway', pr.highway),
				('historic', pr.historic),
				('horse', pr.horse),
				('intermittent', pr.intermittent),
				('junction', pr.junction),
				('landuse', pr.landuse),
				('leisure', pr.leisure),
				('lock', pr.lock),
				('man_made', pr.man_made),
				('military', pr.military),
				('motorcar', pr.motorcar),
				('natural', pr.natural),
				('office', pr.office),
				('oneway', pr.oneway),
				('operator', pr.operator),
				('place', pr.place),
				('population', pr.population),
				('power', pr.power),
				('power_source', pr.power_source),
				('public_transport', pr.public_transport),
				('railway', pr.railway),
				('religion', pr.religion),
				('route', pr.route),
				('service', pr.service),
				('shop', pr.shop),
				('sport', pr.sport),
				('surface', pr.surface),
				('toll', pr.toll),
				('tourism', pr.tourism),
				('tracktype', NULL),
				('tunnel', pr.tunnel),
				('water', pr.water),
				('waterway', pr.waterway),
				('wetland', pr.wetland),
				('wood', pr.wood)
			) as v(tag_name, tag_value)
		where tag_value is not NULL
)
UNION ALL
(
		select pr.osm_id, 'swpa_polygon' as osm_table, pr.id, v.tag_name, v.tag_value, st_transform(pr.way, 32617) as geometry
		from osm.swpa_polygon pr
		cross join lateral (
			values 
				('access', pr.access),
				('admin_level', pr.admin_level),
				('aerialway', pr.aerialway),
				('aeroway', pr.aeroway),
				('amenity', pr.amenity),
				('area', pr.area),
				('barrier', pr.barrier),
				('bicycle', pr.bicycle),
				('brand', pr.brand),
				('bridge', pr.bridge),
				('boundary', pr.boundary),
				('building', pr.building),
				('construction', pr.construction),
				('covered', pr.covered),
				('culvert', pr.culvert),
				('cutting', pr.cutting),
				('denomination', pr.denomination),
				('disused', pr.disused),
				('embankment', pr.embankment),
				('foot', pr.foot),
				('harbour', pr.harbour),
				('highway', pr.highway),
				('historic', pr.historic),
				('horse', pr.horse),
				('intermittent', pr.intermittent),
				('junction', pr.junction),
				('landuse', pr.landuse),
				('leisure', pr.leisure),
				('lock', pr.lock),
				('man_made', pr.man_made),
				('military', pr.military),
				('motorcar', pr.motorcar),
				('natural', pr.natural),
				('office', pr.office),
				('oneway', pr.oneway),
				('operator', pr.operator),
				('place', pr.place),
				('population', pr.population),
				('power', pr.power),
				('power_source', pr.power_source),
				('public_transport', pr.public_transport),
				('railway', pr.railway),
				('religion', pr.religion),
				('route', pr.route),
				('service', pr.service),
				('shop', pr.shop),
				('sport', pr.sport),
				('surface', pr.surface),
				('toll', pr.toll),
				('tourism', pr.tourism),
				('tracktype', pr.tracktype),
				('tunnel', pr.tunnel),
				('water', pr.water),
				('waterway', pr.waterway),
				('wetland', pr.wetland),
				('wood', pr.wood)
			) as v(tag_name, tag_value)
		where tag_value is not NULL
);

create index if not exists osm_entity_tags_tag_name_tag_value_idx on osm_entity_tags (tag_name, tag_value);
create index if not exists osm_entity_tags_geometry_idx on osm_entity_tags using gist (geometry);

ANALYZE osm_entity_tags;
